import { useEffect } from "react";
import type { NextPage } from "next";
import type { GetCategory } from "../../types";
import Head from "../../components/containers/head/Head";
import Layout from "../../components/containers/layout/Layout";
import CategoryCart from "../../components/categories/CategoryCart";

const Categories: NextPage<{ categories: GetCategory[] }> = ({
  categories,
}) => {
  useEffect(() => {
    console.log("categories:", categories);
  }, []);

  return (
    <>
      <Head title="theJs.ir" description="Generated by create next app" />
      <Layout>
        <div className="flex flex-col items-center mb-24">
          <div className="my-14">
            <h1 className="text-2xl text-blue-500 font-bold">مقالات در دسته های زیر منتشر میشوند</h1>
          </div>
          <div className="w-full lg:w-3/4 px-5 lg:px-0">
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-10">
              {categories.map((cat, index) => (
                <CategoryCart key={index} category={cat} />
              ))}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://localhost:8000/api/v1/categories`);

  if (res.ok) {
    const data = await res.json();
    const categories = data.categories as GetCategory[];
    // Pass data to the page via props
    return { props: { categories } };
  } else {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
}

export default Categories;
