import { useEffect } from "react";
import type { NextPage, GetServerSideProps } from "next";
import type { GetPost, UserInterface } from "../../types";
import Head from "../../components/containers/head/Head";
import Layout from "../../components/containers/layout/Layout";
import BlogCart from "../../components/blogs/BlogCart";
import UserProfileImage from "../../components/users/ProfileImage";
import { LinkIcon } from "@heroicons/react/outline";

const UserProfile: NextPage<{ posts: GetPost[]; user: UserInterface }> = ({
  posts,
  user,
}) => {
  useEffect(() => {
    console.log("user:", user);
    console.log("posts:", posts);
  }, []);

  return (
    <>
      <Head title="theJs.ir" description="Generated by create next app" />
      <Layout>
        <div className="flex flex-col items-center justify-center">
          <div className="py-8 flex justify-between items-center gap-10 w-full lg:w-3/4 px-5 lg:px-0 bg-white">
            <div className="flex items-center gap-5 w-full">
              <UserProfileImage image={user?.image_url} name={user?.name} />
              <div className="flex flex-col gap-1 w-full">
                <h1 className="text-base md:text-lg lg:text-2xl text-fuchsia-900 font-bold">
                  {user.name}
                </h1>
                <p className="text-xs md:text-sm lg:text-base text-gray-500"></p>
              </div>
            </div>
            <div className="flex items-start">
              <a target="_blank" href="http://github.com/DevAnsar">
                <LinkIcon className="w-6 h-6 md:w-7 md:h-7 text-fuchsia-900 hover:scale-105" />
              </a>
            </div>
          </div>
          <div className="w-full lg:w-3/4 px-5 lg:px-0">
            <p className="text-sm md:text-base lg:text-xl text-gray-800 text-justify">
              {user?.bio}
            </p>
          </div>
          <div className="w-full lg:w-3/4 px-5 lg:px-0 my-14">
            <span className="text-sm md:text-md lg:text-xl font-bold text-gray-700 mb-5 w-full block">
              مقالات منتشر شده:
            </span>
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-10">
              {posts.map((post, index) => (
                <BlogCart key={index} post={post} withoutuser />
              ))}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

// This gets called on every request
export const getServerSideProps: GetServerSideProps = async (context) => {
  // console.log(context.params);
  if (context.params !== undefined && "username" in context.params) {
    const username = context.params?.username;
    // Fetch data from external API
    const res = await fetch(`http://localhost:8000/api/v1/users/${username}`);

    if (res.ok) {
      const { posts, user }: { posts: GetPost[]; user: UserInterface } =
        await res.json();
      // const posts = data.posts as GetPost[];
      // Pass data to the page via props
      return { props: { posts, user } };
    }
  }
  return {
    redirect: {
      destination: "/",
      permanent: false,
    },
  };
};

export default UserProfile;
