import {useEffect} from "react";
import type { NextPage } from "next";
import type {BlogInterface} from "../types"
import Head from "../components/containers/head/Head";
import Layout from "../components/containers/layout/Layout";

const Home: NextPage<{blogs : BlogInterface[]}> = ({blogs}) => {

  useEffect(()=>{
    console.log("blogs:" ,blogs)
  },[]);

  return (
    <>
      <Head title="theJs.ir" description="Generated by create next app" />
      <Layout>
        <div className="flex flex-col items-center mt-5">
          <span className="text-2xl font-bold text-gray-800 my-5">
            مقاله های مرتبط با برنامه نویسی
          </span>
          <span className="text-3xl font-bold text-blue-600">
            "دِ جِی اِس"
          </span>
        </div>
      </Layout>
    </>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  // const res = await fetch(`https://server.ansarmirzayi.ir/api/v1/blogs`)
  // const data = await res.json()
  // const blogs = data.status ? data.blogs as BlogInterface[] : []
  const blogs : BlogInterface[]= [];
  // Pass data to the page via props
  return { props: { blogs} }
}

export default Home;
