import { useEffect } from "react";
import type { NextPage } from "next";
import type { PostInterface } from "../types";
import Head from "../components/containers/head/Head";
import Layout from "../components/containers/layout/Layout";
import BigBlogCart from "../components/blogs/BigBlogCart";
import IndexSerchBox from "../components/serchers/IndexSerchBox";
import BlogCart from "../components/blogs/BlogCart";

import CategoriesPanel from "../components/categories/Panel";

const Home: NextPage<{ posts: PostInterface[] }> = ({ posts }) => {
  useEffect(() => {
    console.log("posts:", posts);
  }, []);

  return (
    <>
      <Head title="theJs.ir" description="Generated by create next app" />
      <Layout>
        <div className="flex justify-center my-24">
          <div className="w-full lg:w-3/4">
            <IndexSerchBox />
          </div>
        </div>
        <div className="flex justify-center my-24">
          <div className="w-4/5 md:w-3/4">
            <BigBlogCart  post={posts[0]} />
          </div>
        </div>

        <div className="flex justify-center my-24">
          <div className="w-4/5 md:w-3/4">
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-x-12 gap-y-20">
              {posts.map((post,index) => (
                <div className="col-span-1">
                  <BlogCart key={index} post={post} />
                </div>
              ))}
            </div>
          </div>
        </div>

        <CategoriesPanel />
      </Layout>
    </>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://localhost:8000/api/v1/index?recent=1`);
  let posts: PostInterface[] = [];

  if (res.ok) {
    const data = await res.json();
    posts = data.posts as PostInterface[];
  }

  return {
    props: {
      posts,
    },
  };
}

export default Home;
