import { useEffect } from "react";
import { GetServerSideProps } from "next";
import type { NextPage } from "next";
import type { GetPost, GetCategory } from "../../../types";
import Head from "../../../components/containers/head/Head";
import Layout from "../../../components/containers/layout/Layout";
import BlogCart from "../../../components/blogs/BlogCart";

const CategoryOostsPage: NextPage<{
  posts: GetPost[];
  category: GetCategory;
}> = ({ posts, category }) => {
  useEffect(() => {
    console.log("blogs:", posts);
  }, []);

  return (
    <>
      <Head title="theJs.ir" description="Generated by create next app" />
      <Layout>
        <div className="flex flex-col items-center mb-24">
          <div className="my-14">
            <h1 className="text-2xl text-blue-500 font-bold">
               مقالات منتشر شده در دسته ی
              {` ${category?.title} `}
            </h1>
          </div>
          <div className="w-full lg:w-3/4 px-5 lg:px-0">
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-10">
              {posts.map((post, index) => (
                <BlogCart key={index} post={post} />
              ))}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

// This gets called on every request
export const getServerSideProps: GetServerSideProps = async (context) => {
  if (context.params !== undefined && "slug" in context.params) {
    const slug = context.params?.slug;
    // Fetch data from external API
    const res = await fetch(
      `http://localhost:8000/api/v1/categories/${slug}/posts`
    );

    if (res.ok) {
      const { posts, category }: { posts: GetPost[]; category: GetCategory } =
        await res.json();
      // const posts = data.posts as GetPost[];
      // Pass data to the page via props
      return { props: { posts , category } };
    }
  }
  return {
    redirect: {
      destination: "/",
      permanent: false,
    },
  };
};

export default CategoryOostsPage;
